config/routes.rb
Rails.application.routes.draw do
  get 'follow_up/index'
  resources :issue_managements
  resources :loan_managements
  resources :loan_registrations
  resources :rent_managements
  resources :service_providers
  resources :rules
  resources :resources
  resources :cashflow_recons
  resources :saving_recons
  resources :bankaccounts
  resources :inflows
  get 'passwordrepositories/index'
  get 'passwordrepo/index'
  get 'withdrawals/index'
  get 'lodgements/index'
  get 'legacy_ulsterbanks/index'
  get 'expenses/index'
  get 'outflows/index'
  get 'incomes/index'


  resources :deliveries
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'inflows/index'
  resources :ledgers
  resources :savings
  resources :cashflows
  resources :budgets
  resources :employments
  resources :qualifications
  resources :addresses
  resources :telephones
  resources :emails
  resources :people
  resources :departments
  resources :passwordrepositories do
    collection do
      match 'search' => 'passwordrepositories#search', via: [:get, :post], as: :search
    end
  end
  resources :inventories
  resources :withdrawals do
    collection do
      match 'search' => 'withdrawals#search', via: [:get, :post], as: :search
    end
  end


  resources :lodgements do
    collection do
      match 'search' => 'lodgements#search', via: [:get, :post], as: :search
    end
  end
  resources :incomes do
    collection do
      match 'search' => 'incomes#search', via: [:get, :post], as: :search
    end
  end
  resources :inflows do
    collection do
      match 'search' => 'inflows#search', via: [:get, :post], as: :search
    end
  end
  resources :outflows do
    collection do
      match 'search' => 'outflows#search', via: [:get, :post], as: :search
    end
  end
  resources :expenses do
    collection do
      match 'search' => 'expenses#search', via: [:get, :post], as: :search
    end
  end
  resources :legacy_ulsterbanks do
    collection do
      match 'search' => 'legacy_ulsterbanks#search', via: [:get, :post], as: :search
    end
  end


  get 'dashboard/passwords'
  get 'dashboard/financial'
  get 'dashboard/index'
  get 'user/index'
  get 'user/gravatar'
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cashflow_recon.rb
class CashflowRecon < ApplicationRecord
  belongs_to :user
  belongs_to :cashflow
  belongs_to :person
end

app/controllers/cashflow_recons_controller.rb
class CashflowReconsController < ApplicationController
  before_action :set_cashflow_recon, only: [:show, :edit, :update, :destroy]

  # GET /cashflow_recons
  # GET /cashflow_recons.json
  def index
    @cashflow_recons = CashflowRecon.all.paginate(page: params[:page], :per_page => 10).order("created_at DESC")
  end

  # GET /cashflow_recons/1
  # GET /cashflow_recons/1.json
  def show
  end

  # GET /cashflow_recons/new
  def new
    @cashflow_recon = CashflowRecon.new
  end

  # GET /cashflow_recons/1/edit
  def edit
  end

  # POST /cashflow_recons
  # POST /cashflow_recons.json
  def create
    @cashflow_recon = CashflowRecon.new(cashflow_recon_params)

    respond_to do |format|
      if @cashflow_recon.save
        format.html { redirect_to @cashflow_recon, notice: 'Cashflow recon was successfully created.' }
        format.json { render :show, status: :created, location: @cashflow_recon }
      else
        format.html { render :new }
        format.json { render json: @cashflow_recon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashflow_recons/1
  # PATCH/PUT /cashflow_recons/1.json
  def update
    respond_to do |format|
      if @cashflow_recon.update(cashflow_recon_params)
        format.html { redirect_to @cashflow_recon, notice: 'Cashflow recon was successfully updated.' }
        format.json { render :show, status: :ok, location: @cashflow_recon }
      else
        format.html { render :edit }
        format.json { render json: @cashflow_recon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashflow_recons/1
  # DELETE /cashflow_recons/1.json
  def destroy
    @cashflow_recon.destroy
    respond_to do |format|
      format.html { redirect_to cashflow_recons_url, notice: 'Cashflow recon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cashflow_recon
      @cashflow_recon = CashflowRecon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cashflow_recon_params
      params.require(:cashflow_recon).permit(:cashflow_id,:person_id, :user_id, :error_details, :reconciliation_rationale, :correction_amount, :authorised_by, :authorisation_date)
    end
end

app/helpers/cashflow_recons_helper.rb
module CashflowReconsHelper
end

app/views/cashflow_recons/_form.html.erb
<%= simple_form_for(@cashflow_recon) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="jumbotron">
    <div class="control-group">
      <%= f.label :cashflow_id,"Cashflow" %>
      <div class ="controls">
        <%= f.collection_select :cashflow_id, Cashflow.order(:name), :id, :name, include_blank: true %>
      </div>
    </div>
    <br>

    <div class="form-inputs">
      <%= f.input :user_id,:as => :hidden, :input_html => { :value => current_user.id} %>
      <%= f.input :error_details,placeholder:'Error Details...' %>
      <%= f.input :reconciliation_rationale,placeholder:'Enter Rationale...' %>
      <%= f.input :correction_amount,placeholder:'Correction Amount...' %>
      <%= f.input :authorisation_date %>
      <br>
      <div class="control-group">
        <%= f.label :person_id,"Authorised by:" %>
        <div class ="controls">
          <%= f.collection_select :person_id, Person.order(:fullname), :id, :fullname, include_blank: true %>
        </div>
      </div>
      <br>
    </div>

  </div>
  <br>

  <div class="form-actions">
    <%= f.button :submit,"Save" %>
  </div>
<% end %>

app/views/cashflow_recons/edit.html.erb
<% provide(:title, "Edit Cash Recons") %>
<h1>Editing Cashflow Recon</h1>

<%= render 'form', cashflow_recon: @cashflow_recon %>
<br>

<div class="breadcrumb">
  <%= link_to 'View', @cashflow_recon, class:'fa fa-eye' %> |
  <%= link_to 'Back', cashflow_recons_path, class:'fa fa-arrow-left' %>
</div>

app/views/cashflow_recons/index.html.erb
<% provide(:title, "Cash Recons") %>
<p id="notice"><%= notice %></p>

<h1>Cashflow Recons</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Cashflow</th>
      <th>Registed by:</th>
      <th>Correction amount</th>
      <th>Authorised by</th>
      <th>Authorisation date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cashflow_recons.each do |cashflow_recon| %>
      <tr>
        <td><%= link_to cashflow_recon.cashflow.name, cashflow_recon %></td>
        <td><%= cashflow_recon.user.fullname %></td>
        <td><%= cashflow_recon.correction_amount %></td>
        <td><%= cashflow_recon.person.fullname %></td>
        <td><%= cashflow_recon.authorisation_date %></td>
        <td><%= link_to 'View', cashflow_recon, class:'fa fa-eye' %></td>
        <td><%= link_to 'Edit', edit_cashflow_recon_path(cashflow_recon), class:'fa fa-edit' %></td>
        <td><%= link_to 'Delete', cashflow_recon, method: :delete, data: { confirm: 'Are you sure?' }, class:'fa fa-remove' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @cashflow_recons %>
<br>
<div class="breadcrumb">
  <%= link_to 'New Cashflow Recon', new_cashflow_recon_path, class:'fa fa-plus' %>
</div>

app/views/cashflow_recons/new.html.erb
<% provide(:title, "New Cash Recons") %>
<h1>New Cashflow Recon</h1>

<%= render 'form', cashflow_recon: @cashflow_recon %>

<br>
<div class="breadcrumb">
  <%= link_to 'Back', cashflow_recons_path, class:'fa fa-arrow-left' %>
</div>

app/views/cashflow_recons/show.html.erb
<% provide(:title, "View Cash Recons") %>
<p id="notice"><%= notice %></p>



<div class="jumbotron">


  <div>
    <strong>Cashflow:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @cashflow_recon.cashflow.name %>
  </textarea>
  </div>

  <div>
    <strong>User:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @cashflow_recon.user.fullname %>
  </textarea>
  </div>

  <div>
    <strong>Error details:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @cashflow_recon.error_details %>
  </textarea>
  </div>

  <div>
    <strong>Reconciliation rationale:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @cashflow_recon.reconciliation_rationale %>
  </textarea>
  </div>

  <div>
    <strong>Correction amount:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @cashflow_recon.correction_amount %>
  </textarea>
  </div>

  <div>
    <strong>Authorised by:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @cashflow_recon.person.fullname %>
  </textarea>
  </div>

  <div>
    <strong>Authorisation date:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @cashflow_recon.authorisation_date.strftime("%d %b. %Y") %>
  </textarea>
  </div>

</div>

<div class="breadcrumb">
  <%= link_to 'Edit', edit_cashflow_recon_path(@cashflow_recon), class:'fa fa-edit' %> |
  <%= link_to 'Back', cashflow_recons_path, class:'fa fa-arrow_left' %>
</div>