config/routes.rb
Rails.application.routes.draw do
  get 'follow_up/index'
  resources :issue_managements
  resources :loan_managements
  resources :loan_registrations
  resources :rent_managements
  resources :service_providers
  resources :rules
  resources :resources
  resources :cashflow_recons
  resources :saving_recons
  resources :bankaccounts
  resources :inflows
  get 'passwordrepositories/index'
  get 'passwordrepo/index'
  get 'withdrawals/index'
  get 'lodgements/index'
  get 'legacy_ulsterbanks/index'
  get 'expenses/index'
  get 'outflows/index'
  get 'incomes/index'


  resources :deliveries
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'inflows/index'
  resources :ledgers
  resources :savings
  resources :cashflows
  resources :budgets
  resources :employments
  resources :qualifications
  resources :addresses
  resources :telephones
  resources :emails
  resources :people
  resources :departments
  resources :passwordrepositories do
    collection do
      match 'search' => 'passwordrepositories#search', via: [:get, :post], as: :search
    end
  end
  resources :inventories
  resources :withdrawals do
    collection do
      match 'search' => 'withdrawals#search', via: [:get, :post], as: :search
    end
  end


  resources :lodgements do
    collection do
      match 'search' => 'lodgements#search', via: [:get, :post], as: :search
    end
  end
  resources :incomes do
    collection do
      match 'search' => 'incomes#search', via: [:get, :post], as: :search
    end
  end
  resources :inflows do
    collection do
      match 'search' => 'inflows#search', via: [:get, :post], as: :search
    end
  end
  resources :outflows do
    collection do
      match 'search' => 'outflows#search', via: [:get, :post], as: :search
    end
  end
  resources :expenses do
    collection do
      match 'search' => 'expenses#search', via: [:get, :post], as: :search
    end
  end
  resources :legacy_ulsterbanks do
    collection do
      match 'search' => 'legacy_ulsterbanks#search', via: [:get, :post], as: :search
    end
  end


  get 'dashboard/passwords'
  get 'dashboard/financial'
  get 'dashboard/index'
  get 'user/index'
  get 'user/gravatar'
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/saving_recon.rb
class SavingRecon < ApplicationRecord
  belongs_to :user
  belongs_to :saving
  belongs_to :person
end

app/controllers/saving_recons_controller.rb
class SavingReconsController < ApplicationController
  before_action :set_saving_recon, only: [:show, :edit, :update, :destroy]

  # GET /saving_recons
  # GET /saving_recons.json
  def index
    @saving_recons = SavingRecon.all.paginate(page: params[:page], :per_page => 10).order("created_at DESC")
  end

  # GET /saving_recons/1
  # GET /saving_recons/1.json
  def show
  end

  # GET /saving_recons/new
  def new
    @saving_recon = SavingRecon.new
  end

  # GET /saving_recons/1/edit
  def edit
  end

  # POST /saving_recons
  # POST /saving_recons.json
  def create
    @saving_recon = SavingRecon.new(saving_recon_params)

    respond_to do |format|
      if @saving_recon.save
        format.html { redirect_to @saving_recon, notice: 'Saving recon was successfully created.' }
        format.json { render :show, status: :created, location: @saving_recon }
      else
        format.html { render :new }
        format.json { render json: @saving_recon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saving_recons/1
  # PATCH/PUT /saving_recons/1.json
  def update
    respond_to do |format|
      if @saving_recon.update(saving_recon_params)
        format.html { redirect_to @saving_recon, notice: 'Saving recon was successfully updated.' }
        format.json { render :show, status: :ok, location: @saving_recon }
      else
        format.html { render :edit }
        format.json { render json: @saving_recon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saving_recons/1
  # DELETE /saving_recons/1.json
  def destroy
    @saving_recon.destroy
    respond_to do |format|
      format.html { redirect_to saving_recons_url, notice: 'Saving recon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saving_recon
      @saving_recon = SavingRecon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saving_recon_params
      params.require(:saving_recon).permit(:saving_id,:person_id, :user_id, :error_details, :reconciliation_rationale, :correction_amount, :authorised_by, :authorisation_date)
    end
end

app/helpers/saving_recons_helper.rb
module SavingReconsHelper
end

app/views/saving_recons/_form.html.erb
<%= simple_form_for(@saving_recon) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="jumbotron">
    <div class="control-group">
      <%= f.label :saving_id,"Saving" %>
      <div class ="controls">
        <%= f.collection_select :saving_id, Saving.order(:name), :id, :name, include_blank: true %>
      </div>
    </div>
    <br>
    <div class="form-inputs">
      <%= f.input :user_id,:as => :hidden, :input_html => { :value => current_user.id} %>
      <%= f.input :error_details %>
      <%= f.input :reconciliation_rationale %>
      <%= f.input :correction_amount %>
      <%= f.input :authorisation_date %>
      <br>
      <div class="control-group">
        <%= f.label :person_id,"Authorised by:" %>
        <div class ="controls">
          <%= f.collection_select :person_id, Person.order(:fullname), :id, :fullname, include_blank: true %>
        </div>
      </div>
      <br>
    </div>

  </div>
  <br>

  <div class="form-actions">
    <%= f.button :submit, "Save" %>
  </div>
<% end %>

app/views/saving_recons/edit.html.erb
<% provide(:title, "Edit Saving Recons") %>
<h1>Editing Saving Recon</h1>

<%= render 'form', saving_recon: @saving_recon %>
<br>

<div class="breadcrumb">
  <%= link_to 'View', @saving_recon, class:'fa fa-eye'%> |
  <%= link_to 'Back', saving_recons_path, class:'fa fa-arrow-left' %>
</div>

app/views/saving_recons/index.html.erb
<% provide(:title, "Saving Recons") %>
<p id="notice"><%= notice %></p>


<div class="breadcrumb">
  <h3>Saving Recons</h3>
</div>




<table class="table table-hover">
  <thead>
    <tr>
      <th>Saving</th>
      <th>Registered by:</th>
      <th>Correction amount</th>
      <th>Authorised by</th>
      <th>Authorisation date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @saving_recons.each do |saving_recon| %>
      <tr>
        <td><%= link_to saving_recon.saving.name, saving_recon %></td>
        <td><%= saving_recon.user.fullname %></td>
        <td><%= saving_recon.correction_amount %></td>
        <td><%= saving_recon.person.fullname %></td>
        <td><%= saving_recon.authorisation_date %></td>
        <td><%= link_to 'View', saving_recon,class:'fa fa-eye' %></td>
        <td><%= link_to 'Edit', edit_saving_recon_path(saving_recon), class:'fa fa-edit' %></td>
        <td><%= link_to 'Delete', saving_recon, method: :delete, data: { confirm: 'Are you sure?' }, class:'fa fa-remove' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @saving_recons %>
<br>

<div class="breadcrumb">
  <%= link_to 'New Saving Recon', new_saving_recon_path, class:'fa fa-plus' %>
</div>

app/views/saving_recons/new.html.erb
<% provide(:title, "New saving Recon") %>
<h1>New Saving Recon</h1>

<%= render 'form', saving_recon: @saving_recon %>

<br>
<div class="breadcrumb">
  <%= link_to 'Back', saving_recons_path, class:'fa fa-arrow-left' %>
</div>

app/views/saving_recons/show.html.erb
<% provide(:title, "View Saving Recons") %>
<p id="notice"><%= notice %></p>

<div class="jumbotron">


  <div>
    <strong>Cashflow:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @saving_recon.saving.name %>
  </textarea>
  </div>

  <div>
    <strong>User:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @saving_recon.user.fullname %>
  </textarea>
  </div>

  <div>
    <strong>Error details:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @saving_recon.error_details %>
  </textarea>
  </div>

  <div>
    <strong>Reconciliation rationale:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @saving_recon.reconciliation_rationale %>
  </textarea>
  </div>

  <div>
    <strong>Correction amount:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @saving_recon.correction_amount %>
  </textarea>
  </div>

  <div>
    <strong>Authorised by:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @saving_recon.person.fullname %>
  </textarea>
  </div>

  <div>
    <strong>Authorisation date:</strong><br><br>
    <textarea rows="1" cols="80" readonly>
  <%= @saving_recon.authorisation_date.strftime("%d %b. %Y") %>
  </textarea>
  </div>

</div>

<div class="breadcrumb">
  <%= link_to 'Edit', edit_saving_recon_path(@saving_recon), class:'fa fa-edit' %> |
  <%= link_to 'Back', saving_recons_path, class:'fa fa-arrow-left'  %>

</div>