config/routes.rb
Rails.application.routes.draw do
  get 'follow_up/index'
  resources :issue_managements
  resources :loan_managements
  resources :loan_registrations
  resources :rent_managements
  resources :service_providers
  resources :rules
  resources :resources
  resources :cashflow_recons
  resources :saving_recons
  resources :bankaccounts
  resources :inflows
  get 'passwordrepositories/index'
  get 'passwordrepo/index'
  get 'withdrawals/index'
  get 'lodgements/index'
  get 'legacy_ulsterbanks/index'
  get 'expenses/index'
  get 'outflows/index'
  get 'incomes/index'


  resources :deliveries
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'inflows/index'
  resources :ledgers
  resources :savings
  resources :cashflows
  resources :budgets
  resources :employments
  resources :qualifications
  resources :addresses
  resources :telephones
  resources :emails
  resources :people
  resources :departments
  resources :passwordrepositories do
    collection do
      match 'search' => 'passwordrepositories#search', via: [:get, :post], as: :search
    end
  end
  resources :inventories
  resources :withdrawals do
    collection do
      match 'search' => 'withdrawals#search', via: [:get, :post], as: :search
    end
  end


  resources :lodgements do
    collection do
      match 'search' => 'lodgements#search', via: [:get, :post], as: :search
    end
  end
  resources :incomes do
    collection do
      match 'search' => 'incomes#search', via: [:get, :post], as: :search
    end
  end
  resources :inflows do
    collection do
      match 'search' => 'inflows#search', via: [:get, :post], as: :search
    end
  end
  resources :outflows do
    collection do
      match 'search' => 'outflows#search', via: [:get, :post], as: :search
    end
  end
  resources :expenses do
    collection do
      match 'search' => 'expenses#search', via: [:get, :post], as: :search
    end
  end
  resources :legacy_ulsterbanks do
    collection do
      match 'search' => 'legacy_ulsterbanks#search', via: [:get, :post], as: :search
    end
  end


  get 'dashboard/passwords'
  get 'dashboard/financial'
  get 'dashboard/index'
  get 'user/index'
  get 'user/gravatar'
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person


end

app/models/budget.rb
class Budget < ApplicationRecord
  has_many :comments , dependent: :destroy
  has_many :incomes ,  dependent: :destroy
  has_many :expenses,  dependent: :destroy

  accepts_nested_attributes_for :incomes, allow_destroy: true
  accepts_nested_attributes_for :expenses, allow_destroy: true
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/cashflow.rb
class Cashflow < ApplicationRecord

  has_many :inflows, dependent: :destroy
  has_many :outflows, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :cashflow_recons, dependent: :destroy

  accepts_nested_attributes_for :inflows, allow_destroy: true
  accepts_nested_attributes_for :outflows, allow_destroy: true
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :inventory, optional: true
  belongs_to :person, optional: true
  belongs_to :cashflow, optional: true
  belongs_to :saving, optional: true
  belongs_to :delivery,optional: true
  belongs_to :budget,optional: true
  belongs_to :issue_management,optional: true
  belongs_to :saving,optional: true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :person
  accepts_nested_attributes_for :posts,allow_destroy: true
  accepts_nested_attributes_for :comments,allow_destroy: true
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :person

end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :budget
  belongs_to :outflowtype
  belongs_to :person

end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :budget
  belongs_to :inflowtype
  belongs_to :person


end

app/models/inflow.rb
class Inflow < ApplicationRecord
  belongs_to :cashflow
  belongs_to :person
  belongs_to :inflowtype
  belongs_to :bankaccount





end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :items, dependent: :destroy
  belongs_to :department



  accepts_nested_attributes_for :items, allow_destroy: true
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :inventory ,optional: true
end

app/models/ledger.rb
class Ledger < ApplicationRecord
end

app/models/lodgement.rb
class Lodgement < ApplicationRecord
  belongs_to :saving
  belongs_to :financialinstitution
  belongs_to :person



end

app/models/outflow.rb
class Outflow < ApplicationRecord
  belongs_to :cashflow
  belongs_to :person
  belongs_to :outflowtype
  belongs_to :bankaccount
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :emails, dependent: :destroy
  has_many :telephones, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :qualifications, dependent: :destroy
  has_many :employments, dependent: :destroy
  has_many :employmentreferences, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :departments
  has_many :posts
  has_many :deliveries
  has_many :inflows
  has_many :outflows
  has_many :expenses
  has_many :incomes
  has_many :withdrawals
  has_many :lodgements
  has_many :bankaccounts
  has_many :cashflow_recons
  has_many :saving_recons
  has_many :loan_registrations
  has_many :issue_managements
  has_many :corrective_actions


  accepts_nested_attributes_for :emails, allow_destroy: true
  accepts_nested_attributes_for :telephones, allow_destroy: true
  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :qualifications, allow_destroy: true
  accepts_nested_attributes_for :employments, allow_destroy: true
  accepts_nested_attributes_for :employmentreferences, allow_destroy: true
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :delivery

end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :user
end

app/models/rule.rb
class Rule < ApplicationRecord
  belongs_to :user
  belongs_to :rules_category
end

app/models/saving.rb
class Saving < ApplicationRecord
  has_many :lodgements, dependent: :destroy
  has_many :withdrawals, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :saving_recons, dependent: :destroy

  accepts_nested_attributes_for :lodgements, allow_destroy: true
  accepts_nested_attributes_for :withdrawals, allow_destroy: true
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  include Gravtastic
  gravtastic

  has_many :saving_recons
  has_many :cashflow_recons
  has_many :resources
  has_many :rent_managements
  has_many :service_providers
  has_many :rules
  has_many :loan_registrations
  has_many :loan_managements
  has_many :issue_managements
end

app/views/resources/_form.html.erb
<%= simple_form_for(@resource) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="jumbotron">

      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :user_id,:as => :hidden, :input_html => { :value => current_user.id} %>
      <%= f.input :link %>

    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save" %>
  </div>
<% end %>
<br>

app/views/resources/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<br>
<div class="breadcrumb">
  <%= link_to 'View', @resource , class:'fa fa-eye'%> |
  <%= link_to 'Back', resources_path, class:'fa fa-arrow-left' %>
</div>

app/views/resources/index.html.erb
<% provide(:title, "Resources") %>
<p id="notice"><%= notice %></p>


<div class="breadcrumb">
  <h3>Resources</h3>
</div>


<div class="jumbotron">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Logged by</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= link_to resource.name,resource %></td>
        <td><%= resource.description %></td>
        <td><%= resource.user.fullname %></td>
        <td><%= resource.link %></td>
        <td><%= link_to 'View', resource, class:'fa fa-eye' %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) , class:'fa fa-edit' %></td>
        <td><%= link_to 'Delete', resource, method: :delete, data: { confirm: 'Are you sure?' }, class:'fa fa-remove'  %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>


<br>
<div class="breadcrumb">
  <%= link_to 'New Resource', new_resource_path, class:'fa fa-plus'  %>

</div>

app/views/resources/new.html.erb
<% provide(:title, "New resource") %>
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>
<br>
<div class="breadcrumb">
  <%= link_to 'Back', resources_path , class:'fa fa-arrow-left' %>
</div>

app/views/resources/show.html.erb
<% provide(:title, "Resource") %>
<p id="notice"><%= notice %></p>
  <div class="jumbotron">

    <table class="table table-striped">
      <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>Name:</td>
        <td><%= link_to @resource.name,@resource.link %></td>
      </tr>
      <tr>
        <td>Description:</td>
        <td><%= @resource.description %></td>
      </tr>
      <tr>
        <td>Logged by:</td>
        <td><%= @resource.user.fullname %></td>
      </tr>
      <tr>
        <td>Link:</td>
        <td><%= @resource.link %><</td>
      </tr>
      </tbody>
    </table>

  </div>


<div class="breadcrumb">
  <%= link_to 'Edit', edit_resource_path(@resource) , class:'fa fa-edit' %> |
  <%= link_to 'Back', resources_path , class:'fa fa-arrow-left' %>

</div>

<br>