config/routes.rb
Rails.application.routes.draw do
  get 'follow_up/index'
  resources :issue_managements
  resources :loan_managements
  resources :loan_registrations
  resources :rent_managements
  resources :service_providers
  resources :rules
  resources :resources
  resources :cashflow_recons
  resources :saving_recons
  resources :bankaccounts
  resources :inflows
  get 'passwordrepositories/index'
  get 'passwordrepo/index'
  get 'withdrawals/index'
  get 'lodgements/index'
  get 'legacy_ulsterbanks/index'
  get 'expenses/index'
  get 'outflows/index'
  get 'incomes/index'


  resources :deliveries
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'inflows/index'
  resources :ledgers
  resources :savings
  resources :cashflows
  resources :budgets
  resources :employments
  resources :qualifications
  resources :addresses
  resources :telephones
  resources :emails
  resources :people
  resources :departments
  resources :passwordrepositories do
    collection do
      match 'search' => 'passwordrepositories#search', via: [:get, :post], as: :search
    end
  end
  resources :inventories
  resources :withdrawals do
    collection do
      match 'search' => 'withdrawals#search', via: [:get, :post], as: :search
    end
  end


  resources :lodgements do
    collection do
      match 'search' => 'lodgements#search', via: [:get, :post], as: :search
    end
  end
  resources :incomes do
    collection do
      match 'search' => 'incomes#search', via: [:get, :post], as: :search
    end
  end
  resources :inflows do
    collection do
      match 'search' => 'inflows#search', via: [:get, :post], as: :search
    end
  end
  resources :outflows do
    collection do
      match 'search' => 'outflows#search', via: [:get, :post], as: :search
    end
  end
  resources :expenses do
    collection do
      match 'search' => 'expenses#search', via: [:get, :post], as: :search
    end
  end
  resources :legacy_ulsterbanks do
    collection do
      match 'search' => 'legacy_ulsterbanks#search', via: [:get, :post], as: :search
    end
  end


  get 'dashboard/passwords'
  get 'dashboard/financial'
  get 'dashboard/index'
  get 'user/index'
  get 'user/gravatar'
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/telephone.rb
class Telephone < ApplicationRecord
  belongs_to :person

end

app/controllers/telephones_controller.rb
class TelephonesController < ApplicationController
  before_action :set_telephone, only: [:show, :edit, :update, :destroy]

  # GET /telephones
  # GET /telephones.json
  def index
    @telephones = Telephone.all
  end

  # GET /telephones/1
  # GET /telephones/1.json
  def show
  end

  # GET /telephones/new
  def new
    @telephone = Telephone.new
  end

  # GET /telephones/1/edit
  def edit
  end

  # POST /telephones
  # POST /telephones.json
  def create
    @telephone = Telephone.new(telephone_params)

    respond_to do |format|
      if @telephone.save
        format.html { redirect_to @telephone, notice: 'Telephone was successfully created.' }
        format.json { render :show, status: :created, location: @telephone }
      else
        format.html { render :new }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telephones/1
  # PATCH/PUT /telephones/1.json
  def update
    respond_to do |format|
      if @telephone.update(telephone_params)
        format.html { redirect_to @telephone, notice: 'Telephone was successfully updated.' }
        format.json { render :show, status: :ok, location: @telephone }
      else
        format.html { render :edit }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telephones/1
  # DELETE /telephones/1.json
  def destroy
    @telephone.destroy
    respond_to do |format|
      format.html { redirect_to telephones_url, notice: 'Telephone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telephone
      @telephone = Telephone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telephone_params
      params.require(:telephone).permit(:phone, :user_id, :active)
    end
end

app/helpers/telephones_helper.rb
module TelephonesHelper
end

app/views/telephones/_form.html.erb
<%= simple_form_for(@telephone) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :phone %>
    <%= f.input :user_id %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/telephones/edit.html.erb
<h1>Editing Telephone</h1>

<%= render 'form', telephone: @telephone %>

<%= link_to 'Show', @telephone %> |
<%= link_to 'Back', telephones_path %>

app/views/telephones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Telephones</h1>

<table>
  <thead>
    <tr>
      <th>Phone</th>
      <th>User</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telephones.each do |telephone| %>
      <tr>
        <td><%= telephone.phone %></td>
        <td><%= telephone.user_id %></td>
        <td><%= telephone.active %></td>
        <td><%= link_to 'Show', telephone %></td>
        <td><%= link_to 'Edit', edit_telephone_path(telephone) %></td>
        <td><%= link_to 'Destroy', telephone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telephone', new_telephone_path %>

app/views/telephones/new.html.erb
<h1>New Telephone</h1>

<%= render 'form', telephone: @telephone %>

<%= link_to 'Back', telephones_path %>

app/views/telephones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone:</strong>
  <%= @telephone.phone %>
</p>

<p>
  <strong>User:</strong>
  <%= @telephone.user_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @telephone.active %>
</p>

<%= link_to 'Edit', edit_telephone_path(@telephone) %> |
<%= link_to 'Back', telephones_path %>